version: '3.8'

services:
  postgres-dev:
    image: postgres:latest
    container_name: postgres-dev
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: dev_db
    ports:
      - "5433:5432"

  postgres-prod:
    image: postgres:latest
    container_name: postgres-prod
    environment:
      POSTGRES_USER: prod_user
      POSTGRES_PASSWORD: prod_password
      POSTGRES_DB: prod_db
    ports:
      - "5434:5432"
